---
- hosts: localhost
  sudo: yes
  tasks:
  - name: install apache2
    apt: name=apache2 update_cache=yes state=latest
  - name: restart apache
    service: name=apache2 state=restarted
  - name: status apache
    service: name=apache2 state=running
  - name: stop apache
    service: name=apache2 state=stopped
  - name: uninstall apache
    apt: name=apache2 update_cache=yes state=absent
