---
- hosts: localhost
  become: true
  become_user: root
  vars:
    download_url: http://download.oracle.com/otn-pub/java/jdk/8u171-b11/512cd62ec5174c3487ac17c61aaa89e8/jdk-8u171-linux-x64.tar.gz
    download_folder: /opt
    java_name: "{{download_folder}}/jdk1.8"
    java_archive: "{{download_folder}}/jdk-8u171-linux-x64.tar.gz"
# tasks file for java
  tasks:
    - name: get JDK tarball
      get_url:
        url: "{{ download_url }}"
        headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
        dest: "{{ java_archive }}"
      when: (ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "zypper") and ansible_os_family != 'Darwin'

    - file:
        path: '{{ java_name }}'
        state: directory
        mode: 0755
        
    - name: Extract JDK tarball
      unarchive:
        src: '{{ java_archive }}'
        dest: '{{ java_name }}'
        extra_opts: [--strip-components=1]

    - name: Fix ownership
      file: state=directory path={{java_name}} owner=root group=root recurse=yes
      
  #  - name: Clean up
 #     file: state=absent path={{ java_archive }}
